DELIMITER $$

 DROP TRIGGER IF EXISTS   BEFORE_WEB_USER_INSERT $$

 CREATE  TRIGGER BEFORE_WEB_USER_INSERT
 BEFORE INSERT ON WEB_USER FOR EACH ROW BEGIN
declare VAR_CODE INT DEFAULT 0;

SELECT IFNULL(MAX(CODE),1000) INTO VAR_CODE
FROM WEB_USER;
SET NEW.CODE = VAR_CODE+1 ;
END $$


DELIMITER ;

/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */

DELIMITER $$

 DROP TRIGGER IF EXISTS   BEFORE_SS_AREA_INSERT $$

 CREATE  TRIGGER BEFORE_SS_AREA_INSERT
 BEFORE INSERT ON SS_AREA FOR EACH ROW BEGIN
DECLARE VAR_CITY_NAME VARCHAR(50) DEFAULT NULL;
DECLARE VAR_ORDER_ID INT(10) DEFAULT 0;

SELECT IFNULL(MAX(ORDER_ID),0) INTO VAR_ORDER_ID FROM SS_AREA WHERE F_CITY_NO =  NEW.F_CITY_NO;

SELECT CITY_NAME INTO VAR_CITY_NAME FROM SS_CITY WHERE PK_NO = NEW.F_CITY_NO;

SET NEW.CITY_NAME = VAR_CITY_NAME ;
SET NEW.ORDER_ID = VAR_ORDER_ID+1 ;

END $$

DELIMITER ;

