ALTER TABLE `web_user` DROP `EMAIL_VERIFY_CODE`, DROP `EMAIL_VERIFY_EXPIRE`, DROP `MOBILE_VERITY_CODE`, DROP `MOBILE_VERIFY_EXPIRE`;


ALTER TABLE `web_user` ADD `IS_VERIFIED` INT(1) NOT NULL DEFAULT '0' AFTER `PAYMENT_AUTO_RENEW`;