CREATE PROCEDURE PROC_CUSTOMER_PAYMENT_DELETE(IN_PK_NO Integer(11), IN_TYPE VarChar(20))
  NO SQL
BEGIN


        DECLARE VAR_ACC_CUSTOMER_PAYMENTS_PK_NO INT DEFAULT 0;
        DECLARE VAR_F_CUSTOMER_NO INT DEFAULT 0;
        DECLARE VAR_F_PAYMENT_ACC_NO INT DEFAULT 0;
        DECLARE VAR_PAYMENT_CONFIRMED_STATUS INT DEFAULT 0;
        DECLARE VAR_MR_AMOUNT FLOAT DEFAULT 0;
        DECLARE VAR_PAYMENT_REMAINING_MR FLOAT DEFAULT 0;
        DECLARE VAR_TOTAL_PAYMENT_REMAINING_MR FLOAT DEFAULT 0;
        DECLARE VAR_PAYMENT_DATE DATE DEFAULT NULL;

    IF IN_TYPE = 'customer' THEN


            SELECT PK_NO, F_CUSTOMER_NO,F_PAYMENT_ACC_NO,MR_AMOUNT,PAYMENT_REMAINING_MR,PAYMENT_DATE,PAYMENT_CONFIRMED_STATUS INTO VAR_ACC_CUSTOMER_PAYMENTS_PK_NO, VAR_F_CUSTOMER_NO, VAR_F_PAYMENT_ACC_NO, VAR_MR_AMOUNT, VAR_PAYMENT_REMAINING_MR,VAR_PAYMENT_DATE, VAR_PAYMENT_CONFIRMED_STATUS
                FROM ACC_CUSTOMER_PAYMENTS WHERE PK_NO = IN_PK_NO;


                    IF VAR_PAYMENT_CONFIRMED_STATUS = 1 THEN

                            UPDATE SLS_CUSTOMERS
                            SET CUSTOMER_BALANCE_BUFFER = CUSTOMER_BALANCE_BUFFER - VAR_MR_AMOUNT
                            ,CUSTOMER_BALANCE_ACTUAL = CUSTOMER_BALANCE_ACTUAL - VAR_MR_AMOUNT
                            ,CUM_BALANCE = CUM_BALANCE - VAR_PAYMENT_REMAINING_MR
                            WHERE PK_NO = VAR_F_CUSTOMER_NO;


                            UPDATE ACC_PAYMENT_BANK_ACC
                            SET BALACNE_BUFFER = BALACNE_BUFFER - VAR_MR_AMOUNT
                            ,BALANCE_ACTUAL = BALANCE_ACTUAL - VAR_MR_AMOUNT
                            WHERE PK_NO = VAR_F_PAYMENT_ACC_NO;



                    ELSE
                            UPDATE SLS_CUSTOMERS SET CUSTOMER_BALANCE_BUFFER = CUSTOMER_BALANCE_BUFFER - VAR_MR_AMOUNT WHERE PK_NO = VAR_F_CUSTOMER_NO;


                            UPDATE ACC_PAYMENT_BANK_ACC
                            SET BALACNE_BUFFER = BALACNE_BUFFER - VAR_MR_AMOUNT
                            WHERE PK_NO = VAR_F_PAYMENT_ACC_NO;

                    END IF;


                DELETE FROM ACC_BANK_TXN WHERE F_CUSTOMER_PAYMENT_NO = IN_PK_NO;
                DELETE  FROM ACC_CUSTOMER_PAYMENTS WHERE PK_NO = IN_PK_NO;




    ELSEIF IN_TYPE = 'reseller' THEN

            SELECT PK_NO, F_RESELLER_NO,F_PAYMENT_ACC_NO,MR_AMOUNT,PAYMENT_REMAINING_MR,PAYMENT_DATE,PAYMENT_CONFIRMED_STATUS INTO VAR_ACC_CUSTOMER_PAYMENTS_PK_NO, VAR_F_CUSTOMER_NO, VAR_F_PAYMENT_ACC_NO, VAR_MR_AMOUNT, VAR_PAYMENT_REMAINING_MR, VAR_PAYMENT_DATE, VAR_PAYMENT_CONFIRMED_STATUS
            FROM ACC_RESELLER_PAYMENTS WHERE PK_NO = IN_PK_NO;

                IF VAR_PAYMENT_CONFIRMED_STATUS = 1 THEN

                        UPDATE SLS_RESELLERS
                        SET CUM_BALANCE_BUFFER = CUM_BALANCE_BUFFER - VAR_MR_AMOUNT
                        ,CUM_BALANCE_ACTUAL = CUM_BALANCE_ACTUAL - VAR_MR_AMOUNT
                        ,CUM_BALANCE = CUM_BALANCE - VAR_PAYMENT_REMAINING_MR
                        WHERE PK_NO = VAR_F_CUSTOMER_NO;


                        UPDATE ACC_PAYMENT_BANK_ACC
                        SET BALACNE_BUFFER = BALACNE_BUFFER - VAR_MR_AMOUNT
                        ,BALANCE_ACTUAL = BALANCE_ACTUAL - VAR_MR_AMOUNT
                        WHERE PK_NO = VAR_F_PAYMENT_ACC_NO;



                ELSE
                        UPDATE SLS_RESELLERS SET CUM_BALANCE_BUFFER = CUM_BALANCE_BUFFER - VAR_MR_AMOUNT WHERE PK_NO = VAR_F_CUSTOMER_NO;


                        UPDATE ACC_PAYMENT_BANK_ACC
                        SET BALACNE_BUFFER = BALACNE_BUFFER - VAR_MR_AMOUNT
                        WHERE PK_NO = VAR_F_PAYMENT_ACC_NO;

                END IF;



                DELETE FROM ACC_BANK_TXN WHERE F_RESELLER_PAYMENT_NO = IN_PK_NO;
                DELETE FROM ACC_RESELLER_PAYMENTS WHERE PK_NO = IN_PK_NO;




    END IF;



END
/
