CREATE PROCEDURE PROC_SC_BOX_INV_STOCK_HELPER(IN_BOX_LABEL VarChar(20), IN_INV_BOXING_ARRAY VarChar(1024), IN_ROW_COUNT Integer, IN_COL_PARAMETERS Integer, IN_COLUMN_SEPARATOR VarChar(1), IN_ROW_SEPARATOR VarChar(1), USER_ID Integer, IS_UPDATE Integer)
  NO SQL
BEGIN

SET max_sp_recursion_depth=0;


  INSERT INTO R VALUES('helper5');
/*10101010~10~5|10101011~9~3|10101012~10~1|*/
    INSERT INTO R VALUES('helper7');

  CALL PROC_SC_BOX_INV_STOCK(IN_BOX_LABEL, IN_INV_BOXING_ARRAY, IN_ROW_COUNT, IN_COL_PARAMETERS, IN_COLUMN_SEPARATOR, IN_ROW_SEPARATOR, USER_ID, IS_UPDATE,@OUT_STATUS);


INSERT INTO R VALUES(@OUT_STATUS);


END
